import React, { FC } from "react";

export interface MjmlMounterProps {
	children: string;
}

/**
 * !HACK
 * @description
 * This is used to mount the DOM-strings generated by mjml-react's render
 * function, since mjml does not work within storybook
 * @author David Lee
 * @date July 1, 2021
 */
export const MjmlMounter: FC<MjmlMounterProps> = ({ children }) => {
	return <div dangerouslySetInnerHTML={{ __html: children }} />;
};
