name: GraphCDN
on: 
  push: 
    branches: 
      - master 

jobs: 
  main: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2 
        with: 
          node-version: '16.3.0'
          check-latest: true 
      - name: Push to GraphCDN
        run: npx graphcdn push --service makepurple
        env: 
          GRAPHCDN_TOKEN: ${{ secrets.GRAPHCDN_TOKEN }}
